#!/bin/bash

if ! git clang-format --diff; then
	printf "you forgot to run clang-format!\n"
	exit 1
fi

set -e

for item in tests/*; do
	if [ -d "$item" ]; then
		(
			cd $item
			cc -w -o build build.c
			./build
			if ! diff -q -s output expected; then
				printf "the %s test failed!\n" "$item"
				exit 1
			fi
		)
	fi
done

exit 0
